export { openSession } from "./core/browser.js";
export type { Session } from "./core/browser.js";
export { fakePerson } from "./core/data.js";
export type { FakePerson } from "./core/data.js";
export { proxyFromEnvironment } from "./core/proxy.js";
export { defineWorkflow, WorkflowRegistry } from "./core/registry.js";
export { runWorkflow } from "./core/runner.js";
export type { RunOptions } from "./core/runner.js";
export * from "./core/steps.js";
export * from "./core/types.js";
export { captchaSolverFromEnvironment, solveRecaptchaV2 } from "./integrations/captcha-solver.js";
export type { CaptchaSolverConfig, CaptchaSolverService, SolveResult } from "./integrations/captcha-solver.js";
export { recordSession } from "./recorder/recorder.js";
export type { RecordOptions, RecordResult } from "./recorder/recorder.js";
export { recordingToWorkflow, replayRecording } from "./recorder/replay.js";
export type { ReplayOptions, ReplayResult } from "./recorder/replay.js";
export { RecordingBuilder, describeStep, newRecording } from "./recorder/builder.js";
export { listRecordings, loadRecording, saveRecording, loadCheckpoint, clearCheckpoint } from "./recorder/store.js";
export type { Recording, RecordedStep, Checkpoint, Target } from "./recorder/types.js";
export { GENERATORS, generateValues } from "./recorder/generators.js";
export type { GeneratorKind, GeneratedValues } from "./recorder/generators.js";
export { CaptchaGuard } from "./recorder/captcha-guard.js";
export type { CaptchaGuardOptions } from "./recorder/captcha-guard.js";
export { saveAccount, listAccounts, countAccounts, detectAccountVars } from "./recorder/accounts.js";
export type { SavedAccount } from "./recorder/accounts.js";
